package com.nexos.person.commons.enums;

public enum ErrorCode {

        PERSISTENCE_EXCEPTION,
        BUSINESS_EXCEPTION,
        PARAMETERS_REQUIRED_EMPTY,
        INDEX_OUT_OF_BOUNDS_EXCEPTION,
        COULDNT_FIND_PATH_FROM_LOCAL_AND_WORKSPACE,
        FILE_NOT_FOUND_EXCEPTION,
        FAIL_CONNECTION,
        FAIL_CREATE_FOLDER,
        NOT_FOUND_METADATA_EXCEPTION,
        GENERAL_EXCEPTION,
        STOP_EXECUTION,
        ADAPTER_EXCEPTION;



}
